### ISSUE TITLE
No same alternative for previous usage `exports-loader?exports.toString()`

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/exports-loader#52]
- Operating System: macOS 10.15
- Node Version: v12.18.2
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- exports-loader Version: 1.1.0

### Feature Proposal

`exports-loader?type=commonjs&exports=exports.toString()``

Or how can I reference the unknown exported token in loader query?

### Feature Use Case

Don't break previous usage of this loader.

**Comment by evilebottnawi** [comment]
What do you mean `exports.toString()`? Can you provide example? There are not tests for this case

**Comment by JounQin** [comment]
@evilebottnawi It means something like `to-string-loader`.

```js
//... code

module.exports = exports.toString()
```

**Comment by evilebottnawi** [comment]
@JounQin To be honestly it is out of scope `exports-loader`

**Comment by Harkunwar** [comment]
I've trying to polyfill `fetch`, but I'm unable to do it using the latest version. The older version of my code is `exports-loader?self.fetch!whatwg-fetch/dist/fetch.umd` and I think my issue is similar to this issue.

**Comment by evilebottnawi** [comment]
I think here better to use `to-string-loader` + `exports-loader`, because `exports-loader` only for creating exports, also you can call `.toString()` on application side without `to-string-loader`, I want to close the issue, anyway feel free feedback, maybe I missing somethings (for example - real use case and problem)
